language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

gemfile: Gemfile.ci

# Only run a cross-section of 4 builds.
matrix:
  exclude:
    - rvm: 1.8.7
      env: DB=postgres
      gemfile: Gemfile.ci
    - rvm: 1.8.7
      env: DB=sqlite
      gemfile: Gemfile.ci
    - rvm: 1.9.2
      env: DB=sqlite
      gemfile: Gemfile.ci
    - rvm: 1.9.3
      env: DB=sqlite
      gemfile: Gemfile.ci
    - rvm: 1.9.3
      env: DB=mysql
      gemfile: Gemfile.ci

bundler_args: --path=vendor/bundle --without heroku
