language: ruby
rvm:
  - 1.9.3
  - 1.8.7

env:
  - DB=mysql
  - DB=postgres

# Only run a cross-section of 4 builds.
matrix:
  exclude:
    - rvm: 1.8.7
      env: DB=postgres
      gemfile: Gemfile.ci

install: "echo skip bundle install"

before_script:
  - export WORKSPACE=`pwd`/workspace
  - export PATH_TO_INVOICES=`pwd`
  - export PATH_TO_FATFREE=$WORKSPACE/fatfree
  - mkdir $WORKSPACE
  - sh -c "cp config/database.$DB.yml $WORKSPACE/database.yml"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"
  - bash -x ./fatfreecrm_install.sh -c
  - bash -x ./fatfreecrm_install.sh -i
  - bash -x ./fatfreecrm_install.sh -t
  - bash -x ./fatfreecrm_install.sh -u

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
